[package]
name = "cs6600"
version = "0.1.0"
edition = "2021"
description = "cs6600"

[dependencies]
gl = "0.14.0"
glfw = { version = "0.55.0", default-features = false, features = ["wayland"]}

bitflags = "2.5.0"
